# Generated by Django 3.1.5 on 2021-01-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmstrategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='img',
            field=models.URLField(help_text='Ссылка на SVG', verbose_name='Фото'),
        ),
    ]
