# Generated by Django 3.1.5 on 2021-01-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmstrategy', '0002_auto_20210118_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='img_place',
            field=models.CharField(default='LEFT_SIDE_', help_text='Сторона на которой будет стоять фото.', max_length=255, verbose_name='Место фото'),
        ),
    ]
