# Generated by Django 3.1.5 on 2021-01-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmstrategy', '0003_advantage_img_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='img_place',
            field=models.CharField(choices=[('LEFT_SIDE_', 'Слева'), ('RIGHT_SIDE_', 'Справа')], default='LEFT_SIDE_', help_text='Сторона на которой будет стоять фото.', max_length=255, verbose_name='Место фото'),
        ),
    ]
